### ISSUE TITLE
Feature request: add config to pass-through img tags so that sizing can be specified

### ISSUE THREAD

**Issue by esimkowitz** [mysticmind/reversemarkdown-net#117]
The GFM spec allows for HTML `img` tags to be passed through to a .md file, which enables more advanced formatting such as providing width and height measurements. I'm willing to take up adding this as a feature if you sign off. My idea is to either create a new config just for passing through the img tag or to create a more general config where a list of tags to ignore can be passed in which they want passed through to the MD file. Then, when the converter is being generated, The tag-specific converters that correspond to the tags in the passthrough list would not be initialized.

Let me know what you think!

**Comment by rexxitall** [comment]
I will not sign of from github ;) 
The problem with your idea is that it will work globally.
My idea was to have something simple just in case that you have to resize a image you can force it. Sorry, you was responding so late, that my idea is got lost why i want to have it. I guess for a function which provides and process help files. I was never happy the way autodesk provides help, so i wrote my own parser and database to find things. Its M based, which i consider as a great way to have help files in html. Autodesk has for example some images in their help files. Just not the way and size i like. That might be the result why i came on that idea :) I will soon work again on that module. Maybe then i get my initial thougt about that back :) 20 Years ago i inventet something like MD for a firefighter web page of my hometown. MD wasn invented and i was looking for something that could help me on my weekly repoarts. My image tag that days has had such a size function :)But as said, if i struggle again on this problem, i would like to discuss it with you again :)
