### ISSUE TITLE
Feature request: allow passthrough of img tags to markdown file for more advanced formatting

### ISSUE THREAD

**Issue by esimkowitz** [mysticmind/reversemarkdown-net#118]
The GFM spec allows for HTML `img` tags to be passed through to a .md file, which enables more advanced formatting such as providing width and height measurements. I'm willing to take up adding this as a feature if you sign off. My idea is to either create a new config just for passing through the img tag or to create a more general config where a list of tags to ignore can be passed in which they want passed through to the MD file. Then, when the converter is being generated, The tag-specific converters that correspond to the tags in the passthrough list would not be initialized.

Let me know what you think!

**Comment by mysticmind** [comment]
@esimkowitz acknowledge the same, will look at adding the feature by next week.

**Comment by mysticmind** [comment]
Fixed via dd96654facffeb28583271eb363d98fbe9762396

**Comment by mysticmind** [comment]
@esimkowitz sorry that it took so long for me to get to this item, was held up with more pressing things to take care personally.
