### ISSUE TITLE
Question: html document with data-absolute-enabled has the div section with "style: position=absolute" converted to the wrong location of the document in markdown. Is there any option to fix that?

### ISSUE THREAD

**Issue by xmh1999** [mysticmind/reversemarkdown-net#127]

**Comment by mysticmind** [comment]
@xmh1999 please note that HTML to markdown conversion does not take into account style or class attributes (no library can handle these things). Hence any CSS position properties will be ignored. 

If you want to ensure the position of an HTML element, do a pre-processing step to manipulate HTML using say HTMLAgilityPack to move the element in the Html document accordingly before converting to markdown.
