### ISSUE TITLE
Nested list render issue

### ISSUE THREAD

**Issue by FanrayMedia** [mysticmind/reversemarkdown-net#14]
I tried the following html

    <ul>
        <li>Apple</li>
        <li>Microsoft</li>
        <ul>
            <li>IBM</li>
            <li>Cisco</li>
        </ul>
    </ul>

### Expected behavior
*   Apple
*   Microsoft
    *   IBM
    *   Cisco

### Actual Output

the converted output is in the link below and it has 2 issues

https://jbt.github.io/markdown-editor/#49JVcCwoyEnl0lXwzUwuyi/OTyvh4lLQVfB08gVRzpnFyflcXFwA

1. the nested list is not indented correctly. It is actually missing 1 space to make it correct
2. notice the empty lines before and after the converted markdown result, those should be trimmed

### Steps to reproduce

I used the latest nuget package, and the code to reproduce

            var html = @"
        <ul>
            <li>Apple</li>
            <li>Microsoft</li>
            <ul>
                <li>IBM</li>
                <li>Cisco</li>
            </ul>
        </ul>
        ";

            var converterReverseMarkdown = new ReverseMarkdown.Converter();
            var mdReverseMarkdown = converterReverseMarkdown.Convert(html);

**Comment by mysticmind** [comment]
@FanrayMedia I believe nested list should have a wrapping like `<li><ul></ul></li>` but the html which you described in the bug does not have the `li` tag wrapping the `ul` block. Isn't the html incorrect in this case?

**Comment by FanrayMedia** [comment]
@mysticmind You are absolutely correct.  I got the html output from using Open Live Writer, therefore I overlooked it.  I have just opened an issue on [OLW repo](https://github.com/OpenLiveWriter/OpenLiveWriter/issues/690).  This [Stackoverflow question](https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list) is helpful explaining the correct way to do nested html list for anyone who is interested. Thank you!

**Comment by FanrayMedia** [comment]
@mysticmind I actually tried again with the correct html and still seem to get wrong markdown output, check it out https://jbt.github.io/markdown-editor/#49JV8CxJzTVUAAIuBQjHiIsLAA==

My code

            var html = @"<ul>
			  <li>Item1
				<ul>
				  <li>Item2</li>
				</ul>
			  </li>
			</ul>	";
            var converter = new ReverseMarkdown.Converter();
            string result = converter.Convert(html);

**Comment by mysticmind** [comment]
Fixed and v1.4.0 available in nuget.
