### ISSUE TITLE
Blank lines being added on things that are getting dropped/bypassed

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mysticmind/reversemarkdown-net#155]
```powershell
    $Splat = @{
        #Content                  = $BlogContent.Content
        Path                     = $FilePath
        DestinationPath          = "$PSScriptRoot\OutputBlogs\$($FileName).md"
        UnknownTags              = 'Bypass'
        GithubFlavored           = $true
        RemoveComments           = $true
        SmartHrefHandling        = $true
        RulesBefore              = $RulesBefore
        RulesAfter               = $RulesAfter
        DefaultCodeBlockLanguage = 'powershell'
    }
```

There's a lot of blank lines that stay after your library goes thru the HTML. It seems that every time some tags are removed those are replaced by blank lines? Could it be those are totally skipped maybe?

![image](https://user-images.githubusercontent.com/15063294/112755350-90d11580-8fe0-11eb-9489-31d8c749515f.png)

**Comment by mos379** [comment]
I discovered that as well, but ende up cleaning the result with simple postprocessing.
```
result = result.Replace("\n\n", "\n");
result = result.Replace("\r\n\r\n", "\r\n");
result = result.Replace("\r\n\r\n", "\r\n");
if (result.StartsWith("\r\n"))
{
	result = result.TrimStart('\r', '\n');
}
return result;
```
so maybe we can have something like this by default?

**Comment by mysticmind** [comment]
> I discovered that as well, but ende up cleaning the result with simple postprocessing.
> 
> ```
> result = result.Replace("\n\n", "\n");
> result = result.Replace("\r\n\r\n", "\r\n");
> result = result.Replace("\r\n\r\n", "\r\n");
> if (result.StartsWith("\r\n"))
> {
> 	result = result.TrimStart('\r', '\n');
> }
> return result;
> ```
> 
> so maybe we can have something like this by default?

I have added some cleanup and processing of newlines in 3.21.0, please take latest and check if it has become better. Possibly you don't need to do this step.

**Comment by mos379** [comment]
seems to be a bit better. need to check more in detail

**Comment by mysticmind** [comment]
Closing this, please file a new issue if you see any further issues.
