### ISSUE TITLE
Give the assembly a strong name

### ISSUE THREAD

**Issue by oalt** [mysticmind/reversemarkdown-net#170]
Please sign your assembly to get a strong name. I use it in my application and here only signed assemblies are allowed to get a strong name for COM interop.

**Comment by mysticmind** [comment]
@oalt you could use https://github.com/dsplaisted/strongnamer to automatically sign the referenced assemblies in your project.

**Comment by oalt** [comment]
Thank you for the tip. That solved also my problem.
