### ISSUE TITLE
Newline is added when first tag is a <p> tag

### ISSUE THREAD

**Issue by SpaceOgre** [mysticmind/reversemarkdown-net#181]
Hi,

If the HTML text to convert starts with a <p> tag a newline is added first, is this how it should be?
```html
<p>
text
</p>
```
becomes
```
\n
text
```

**Comment by mysticmind** [comment]
@SpaceOgre Acknowledge seeing the issues which you have posted, I am unavailable for couple of days, will revert to you once I am available.

**Comment by mysticmind** [comment]
This is addressed in v3.21.0 via https://github.com/mysticmind/reversemarkdown-net/commit/625b4758300b1f939a1d5d3ce9b5b9e55e8ac839
