### ISSUE TITLE
[Bug] Strong tags should have its content trimed just like em

### ISSUE THREAD

**Issue by SpaceOgre** [mysticmind/reversemarkdown-net#182]
It is not valid markdown for bold to start or end with a space.
So the content for these tags should be trimed: strong, b

Edit:
----
Saw now that this is already down for em: https://github.com/mysticmind/reversemarkdown-net/blob/e8b2cce1a24f4596112c12196a086358f5d8f411/src/ReverseMarkdown/Converters/Em.cs#L34
But not for strong.

**Comment by mysticmind** [comment]
Fixed via ef2faa929e24fde531ba4ceb0a4752f440574c11
