### ISSUE TITLE
Incorrect handling for line breaks within tags 

### ISSUE THREAD

**Issue by mos379** [mysticmind/reversemarkdown-net#246]
In #67 the handling was changed to keep line breaks within a tag  which leads to invalid Markdown syntax when trying to revert it back to html.
test<b><br/>test</b> is converted to 
`test**
test**`

I'm haven't looked at your code, but when translating to markdown and a <br> is discovered within tags, then they should be removed in my view, because it is bad style in html

**Comment by mysticmind** [comment]
Fixed via ef2faa929e24fde531ba4ceb0a4752f440574c11

**Comment by mos379** [comment]
seems to work well, thanks:)
