### ISSUE TITLE
wrong syntax when converting HTML tables

### ISSUE THREAD

**Issue by doggy8088** [mysticmind/reversemarkdown-net#25]
I try to convert the following HTML into Markdown.

```html
<div>
  <table>
    <tr>
      <td>aaa</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
      <td>5</td>
    </tr>
    <tr>
      <td>6</td>
      <td>7</td>
      <td>8</td>
      <td>9</td>
      <td>9</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
      <td>5</td>
    </tr>
    <tr>
      <td>7</td>
      <td>7</td>
      <td>8</td>
      <td>9</td>
      <td>0</td>
    </tr>
  </table>
</div>
```

Use the following code snippet:

```cs
bool githubFlavored = true;
bool removeComments = true;
var config = new ReverseMarkdown.Config(ReverseMarkdown.Config.UnknownTagsOption.PassThrough, githubFlavored: githubFlavored, removeComments : removeComments);
var converter = new ReverseMarkdown.Converter(config);
var markdown = converter.Convert(html);
```

The result is:

```md
| aaa | 2 | 3 | 4 | 5 |
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```

The expected result should be:

```md
| aaa | 2 | 3 | 4 | 5 |
|-----|---|---|---|---|
| 6 | 7 | 8 | 9 | 9 |
| 1 | 2 | 3 | 4 | 5 |
| 7 | 7 | 8 | 9 | 0 |
```

**Comment by mysticmind** [comment]
@doggy8088 You sample does not have any `<th>...</th>` tags for processing it as header. Looks like an invalid issue. Can you please clarify?

**Comment by doggy8088** [comment]
@mysticmind I see. I tried `<th>`.  It works.  Thanks!

But I think even I don't have a `<th>` tag, you still need to generate a valid Markdown table.

**Comment by PromoFaux** [comment]
It seems that `HTML` is happy to render a table without `<th>` tags (but obviously you don't get the formatting for the header row), whereas markdown insists there _must_ be a header row.

I wonder if, for the sake of nicely formatted output, any table the parser comes across should have an underline added after the first row, regardless of wether or not it is a `<th>` row?

```html
<div>
  <table>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>  
    </tr>
  </table>
</div>
```
Renders as: 
<div>
  <table>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>  
    </tr>
  </table>
</div>

----

```html
<div>
  <table>
    <tr>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
    </tr>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>  
    </tr>
  </table>
</div>
```
Renders as:

<div>
  <table>
    <tr>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
    </tr>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>  
    </tr>
  </table>
</div>

----

```
|1|2|3|4|
|1|2|3|4|
```
Renders as:

|1|2|3|4|
|1|2|3|4|

----

```
|1|2|3|4|
|-|-|-|-|
|1|2|3|4|
```
Renders as:

|1|2|3|4|
|-|-|-|-|
|1|2|3|4|

**Comment by mysticmind** [comment]
@PromoFaux and @doggy8088 agree and makes sense. Marking this as a bug.

**Comment by mysticmind** [comment]
GFM requires a header in table. It is a mixed bag that there are markdown parsers that support parsing with or without header. 

I am thinking the following:
- In the case of GFM, we can add logic to add a header for sure. 
- For non GFM case, we can make it optional and can be added via a flag. so there are configurable options.

Thoughts?

**Comment by mysticmind** [comment]
@doggy8088  Take a look at https://stackoverflow.com/questions/17536216/create-table-without-header-in-markdown. I feel that it is incorrect to mark the first column as header if the source html does not have `th` tag. 

I think it would help to add a solution for the cases which does not have `th` tags to use a empty header as mentioned in the above SO answers:

```
[]()  | 
------|------
Foo | Bar
```
or
```
| <!-- -->    | <!-- -->    |
|-------------|-------------|
| Foo         | Bar         |
```

**Comment by doggy8088** [comment]
@mysticmind The SO's answer expand my knowledge.   I don't even know there are parsers that do support tables without headers before.  😛 

I agree your thoughts.  Providing an option is a good design choose. 👍
