### ISSUE TITLE
Is there a possibility to process <span> somehow instead of just ignoring it

### ISSUE THREAD

**Issue by mysticmind** [mysticmind/reversemarkdown-net#254]
### Discussed in https://github.com/mysticmind/reversemarkdown-net/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **mos379** December 28, 2021</sup>
I have some html which uses <span> tags to separate items and I'd like simply to process them somehow. 
For example just adding a newline after the enclosed text.

Is this somehow possible?</div>

**Comment by mysticmind** [comment]
This is address in v 3.21.0

**Comment by mos379** [comment]
seems to work quite well, but I discovered one situation where I'm not sure where the blank between the list and paragraph comes from?
```
<ul>
<li><span style="font-weight: 400;">Demonstrate the single-arm overhead lunge and the expectations for the synchronization of the movement.</span><span style="font-weight: 400;"><br />
</span></li>
<li><span style="font-weight: 400;">Athletes should increase weight with each set.</span><span style="font-weight: 400;"><br />
</span></li>
</ul>
<p><b>3 Sets</b><span style="font-weight: 400;"><br />
</span><span style="font-weight: 400;">10 Synchronized Overhead Lunges with partner</span></p>
```
ends up in 
```
- Demonstrate the single-arm overhead lunge and the expectations for the synchronization of the movement.
- Athletes should increase weight with each set.
 
**3 Sets**
10 Synchronized Overhead Lunges with partner
```

**Comment by mysticmind** [comment]
There has to be a line space between list and the following paragraph. This looks to be correct.

**Comment by mos379** [comment]
the thing is that it is actually a whitespace not just a LF
but I'm ok with that.
