### ISSUE TITLE
Formatted/Indented html is parsed incorrectly

### ISSUE THREAD

**Issue by mos379** [mysticmind/reversemarkdown-net#255]
Formatted/Indented html is parsed incorrectly
```
<thead>\n<tr>\n<th style=\"text-align: left;\">Progression</th>\n<th style=\"text-align: left;\">Focus</th>\n</tr>\n</thead>
```
it results in 
```
|\n Progression |\n Focus |\n| --- | --- |
```

**Comment by mysticmind** [comment]
This is possibly a regression with handling the line breaks, will have a look at it.

**Comment by mos379** [comment]
thanks for the fast response!

**Comment by mysticmind** [comment]
Probably simple cases like `style="text-align: left;"` could be handled. Let me ponder on this a bit, will keep you posted.
