### ISSUE TITLE
Suggestion: dl, dt, dd could render as lists

### ISSUE THREAD

**Issue by brianary** [mysticmind/reversemarkdown-net#282]
Mapping `<dl>` to an unordered list seems like a good fit, with `<dt>` mapping to `<li>`, and `<dd>` adding paragraph blocks to the previous list item.

**Comment by mysticmind** [comment]
Looks like a good suggestion for conversion of dl,dt and dd, will look at implementing it.

**Comment by evilz** [comment]
Any news on this ?

**Comment by mysticmind** [comment]
@evilz quick note, I have added implementation to handle definition lists, will be available in the up coming release. I am looking at what other ones which I can include for 3.24.0.

**Comment by evilz** [comment]
So cool !
