### ISSUE TITLE
StringUtils internal methods can be useful for custom coverters

### ISSUE THREAD

**Issue by IhnatKlimchuk** [mysticmind/reversemarkdown-net#331]
I've faced with an issue that I have to parse `<a>` tag with `<div><img></div>`. Default `A` converter will try to `EscapeLinkText`, what ruin the result.  I understand, that my case quite unique and it may be hard to cover it with current project structure, but I'm having a hard time creating a custom `A` converter, as most methods in `StringUtils` are internal.

Can you please make all methods in `StringUtils` public? UPD: IsSchemeWhitelisted from Config too, please

Thank you in advance and have a great day!

**Comment by mysticmind** [comment]
Acknowledge your message, I can definitely make those public, will look at it and keep you posted in a day or 2.

**Comment by mysticmind** [comment]
@IhnatKlimchuk Sorry that it has been away for couple of weeks, had some family emergency so couldn't get to this. I will revert to you this week.

**Comment by IhnatKlimchuk** [comment]
@mysticmind no worries, take your time. It's not a blocker as code is open and can be copied & modified. Hope everything is good with you and your family.

**Comment by mysticmind** [comment]
Fixed via 307cc27
