### ISSUE TITLE
Add support to strikethrough elements

### ISSUE THREAD

**Issue by darklinkpower** [mysticmind/reversemarkdown-net#356]
Currently elements `s`, `del` and `strike` which can be used for strikethrough are not processed.

In markdown strikethrough elements should be:

`~~Text~~`

Displayed as:
~~Text~~

**Comment by mysticmind** [comment]
I will schedule to implement it.

**Comment by mysticmind** [comment]
https://github.com/mysticmind/reversemarkdown-net/releases/tag/4.1.0
