### ISSUE TITLE
Net Standard 2.0 support?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mysticmind/reversemarkdown-net#359]
Would you consider adding back NET Standard 2.0 support? It's the only one that allows to work .NET libraries with PowerShell 5.1 which is built-in into modern Windows versions. Dropping it, means no PS 5.1 support and only PS 7+ which is separate download. 

- https://github.com/mysticmind/reversemarkdown-net/releases/tag/4.0.0

I use your project in [MarkdownPrince](https://github.com/EvotecIT/MarkdownPrince) which is used by PowerShell community.

**Comment by mysticmind** [comment]
Sure, will add it back.

**Comment by mysticmind** [comment]
Fixed via 59961d191e919824d21ab65c61ee8ea9f35e3610

**Comment by mysticmind** [comment]
https://github.com/mysticmind/reversemarkdown-net/releases/tag/4.1.0
