### ISSUE TITLE
Link and image text and href are not escaped correctly

### ISSUE THREAD

**Issue by ian-craig** [mysticmind/reversemarkdown-net#38]
In a Markdown link `[text](href)` or imagee `![text](href)` the `text` should not contain `[` or `]` and the href should not contain `)`, `(` or ` ` (space) because these would terminate the section.

Text is also allowed to have newlines, but not multiple adjacent newlines.

All of the above are allowed in HTML, so we need to escape them when converting to Markdown.

**HTML:**
```html
<img alt="foo ]

bar" src="https://avatars3.githubusercontent.com/u/2031632?s=88&v=4&desc=Foo Bar&code=asd)asd" />
```

**Current Markdown:**
```
![foo ]

bar](https://avatars3.githubusercontent.com/u/2031632?s=88&v=4&desc=Foo Bar&code=asd)asd)
```
>![foo ]
>
>bar](https://avatars3.githubusercontent.com/u/2031632?s=88&v=4&desc=Foo Bar&code=asd)asd)

**Expected Markdown:**
```
![foo \]
bar](https://avatars3.githubusercontent.com/u/2031632?s=88&v=4&title=Foo%20Bar&code=asd%29asd)
```
> ![foo \]
>bar](https://avatars3.githubusercontent.com/u/2031632?s=88&v=4&title=Foo%20Bar&code=asd%29asd)

**Comment by mysticmind** [comment]
@ian-craig FYI, v3.6.0 was released earlier today.
