### ISSUE TITLE
Inline markup with leading/trailing white-spaces result in invalid markdown

### ISSUE THREAD

**Issue by AlexanderInova** [mysticmind/reversemarkdown-net#388]
## Description
Inline markup (emphasis and strong emphasis) surrounded by leading or trailing white spaces results in incorrectly flanked markdown, causing it not to render as expected.

See https://spec.commonmark.org/0.31.2/#example-351 for further details.

## Steps to reproduce
Use HTML that contains leading or trailing white spaces within inline markup like ```<em>```, ```<strong>```, ```<b>```, ```<i>``` or similar. 

Here is an example:
```csharp
var html = """
           This <em>results</em> in <strong>invalid </strong> markdown.
           """;
Console.WriteLine(new ReverseMarkdown.Converter(new ReverseMarkdown.Config()).Convert(html));
```

This results in: 
```text
This *results* in **invalid ** markdown.
```

Since the second ```**``` is not flanked correctly, it doesn't render as expected (according to input HTML):
This *results* in **invalid ** markdown.

**Comment by AlexanderInova** [comment]
@mysticmind I assume that issue is that the `Chomp` extension function does not call `Trim` when `all = true`.

**Comment by mysticmind** [comment]
@AlexanderInova I am unavailable for few days, will revert to you once I am available.

**Comment by AlexanderInova** [comment]
@mysticmind In order to try to speed this a little up, I created a PR #390 that might fix the issue. I would really appreciate your support. 

To be honest: I didn't really read all the code of this repository, so please review this small change carefully and ensure that this doesn't mess up other functionality of your library.

**Comment by mysticmind** [comment]
Hey @AlexanderInova, I was completely unavailable for few weeks now with a few of personal  urgency/events. I will surely take a look tonight and do a release accordingly.

Apologies to keep you waiting and thanks for the PR.

**Comment by mysticmind** [comment]
4.4.0 is released to NuGet with a fix for this. Please run a test and keep me posted.

**Comment by AlexanderInova** [comment]
We integrated your update into our project and it seems to work just fine. Our QA just approved the internal rollout. 

Thank you very much. You should receive a little donation for your investigation shortly. We appreciate your work. :heart:

**Comment by mysticmind** [comment]
@AlexanderInova Glad to hear this and thank you so much for the sponsor amount, appreciate it 👍

On a side note, I have seen large companies use the lib but never bothered to sponsor even a token amount till date.
