### ISSUE TITLE
 Code updates and migration to .NET Standard

### ISSUE THREAD

**Issue by agatlin** [mysticmind/reversemarkdown-net#4]
I've cleaned up the code and refactored it slightly to improve performance. I would like to upload my changes from my local branch. 

I also am in the process to migrating this code so it will work with .NET Standard. I wondered if you might be interested in having me upload those changes as well.

**Comment by mysticmind** [comment]
@agatlin Thanks for your interest in this project. I am happy to accept pull requests (PR's) for others to contribute to this project. 

"Clean up of code and refactoring it slightly to improve performance" is too broad a term without the relevant details. Appreciate if you could send a PR with details for me to review it. 

With regards to supporting .Net standard, I am already looking at it including migrating the project to use the new csproj.  If you have made significant amount of progress on this, please feel free to send me another PR for it. Otherwise, I would suggest you to wait for my changes to be available and you can submit your changes later.

**Comment by agatlin** [comment]
Yes, I have completely migrated the project to use CsProj and NetCore1.1/NetStandard 1.6.  I have it completely working and all your existing unit tests pass.

With regard to the updates for performance improvement on the current branch, I updated every single file, so it might take me a while to explain everything I did. Basically, I inlined any statements I could, converted concatenated strings to use String.Format, replaced "" with String.Empty (for coding practice as opposed to performance.),  and made similar changes. Of course, all unit tests still pass. 

When I tried to upload a pull request, Visual Studio 2017 failed. I am not sure why. Do I nee special permissions to upload a pull request here?

**Comment by agatlin** [comment]
Here is the error I am getting when I try to upload the branch from command prompt through `HTTPS`. I am also getting errors with `SSH`. It seems as if I do not have permission.

```
E:\Projects\reversemarkdown-net>git push --set-upstream origin code-cleanup
remote: Permission to mysticmind/reversemarkdown-net.git denied to agatlin.
fatal: unable to access 'https://agatlin:xxxxxxxxxxxxxxx@github.com/mysticmind/reversemarkdown-net.git/': The requested URL returned error: 403
```

`code-cleanup` is the name of the local branch I created. I was neither able to push this branch or push changes to master.

**Comment by mysticmind** [comment]
I wrapped up the migration which I was working on and the latest changes available in master branch targets .Net 4.5, .Net 4.6 and .Net standard 1.6. I have released pre-release version 1.0.0-beta1 in nuget.

Based on your above comments, it looks like you are not familiar with the github workflow of contributing to OSS projects. In a nutshell, 1)you will need to fork this project into our own account 2)create a working/feature branch from master 3)do you changes on  it 4)Send a Pull Request which will appear in the original project for review and if everything good, the owner of the project will merge the PR. Refer to this link http://www.asmeurer.com/git-workflow/ for more info.

With regards to the cleanup, refactoring and performance improvements, work on top of the latest changes in master.  Use the git workflow which I have described above and send me a PR. Feel  free to get back to me if you face any issues, happy to help out!

**Comment by mysticmind** [comment]
@agatlin you can read through the previous comment and provide a PR for the performance related enhancements.

v1.0.0 is published to Nuget with support for  .Net 4.5, .Net 4.6 and .Net standard 1.6. Closing this one.

**Comment by agatlin** [comment]
I recommend also specifically adding .NET Core 1.1 into the target frameworks. There are a lot of folks (such as myself) who may be specifically interested in a .NET Core target as opposed to specifically a .NET Standard version.

**Comment by mysticmind** [comment]
Published .Net Standard version of lib is compatible with both .Net Core 1.0 and 1.1.
