### ISSUE TITLE
Headings inside tables break Markdown tables

### ISSUE THREAD

**Issue by ian-craig** [mysticmind/reversemarkdown-net#44]
Example HTML:
```html
<table>
    <tr><th><h2>Heading</h2></th><tr>
    <tr><td>Content</td><tr>
</table>
```
> <table>
>    <tr><th><h2>Heading</h2></th></tr>
>    <tr><td>Content</td></tr>
></table>

Current Markdown:
```
| 
## Heading

|
| --- |
| Content |
```
> | 
>## Heading
>
>|
>| --- |
>| Content |

One possible expected Markdown:
```
| **Heading** |
| --- |
| Content |
```
>| **Heading** |
>| --- |
>| Content |

@mysticmind This formatting bug is a bit more of a design decision, so I don't want to rush to sending a PR for a solution.

Converting to bold would be an easy fix, but obviously the resulting text isn't quite as emphasised as a heading.

Alternatively, sometimes headings have inline style: `<h2 style="font-size: .... ;"> ...` which we could convert to `<span style="font-size: .... ;"> ...` to preserve more of the original formatting. If this formatting doesn't exist we could make one up, but this is more of a special case and seems more risky.

I'm happy to send a PR for the bold fix if this is a direction you're happy with.

**Comment by mysticmind** [comment]
@ian-craig There is idiomatic example or usage of this case in the GFM tables. I would suggest to just keep the heading text (ignore the heading tag) for all heading tags if the parent is a table. So the fix has to be applied in the Heading converter logic.

Thoughts?

**Comment by ian-craig** [comment]
Sounds good to me. I don't think there's a perfect solution so stripping these out seems the safest.

PR sent 🚀
