### ISSUE TITLE
Use Nuget MysticMind.HtmlAgilityPack 1.4.9.4 for release version

### ISSUE THREAD

**Issue by mysticmind** [mysticmind/reversemarkdown-net#6]
The original HtmlAglityPack project in codeplex did not have a .Net Standard version and I created a [forked version](https://github.com/mysticmind/mysticmind-htmlagilitypack) with support for .Net Standard which has been maintained for some time now.  

The original HtmlAglityPack project in codeplex has a new maintainer, repo has been moved from Codeplex to Github https://github.com/zzzprojects/html-agility-pack. The new maintainer contacted me and used my forked code changes in the original project to release a beta version(pre-release) targeting .Net Standard version https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.5.0-beta2.

I will use my forked version for this project to publish a release version until the original project published a release version in Nuget.

**Comment by agatlin** [comment]
There is actually already a version of the HTML Agility Pack for .NET Core available on Nuget. This is the version I used for my .NET Core / .NET Standard version of Reverse Markdown. This version works and performs very well.
https://www.nuget.org/packages/HtmlAgilityPack.NetCore/
The GitHub repository for the source is https://github.com/zulfahmi93/HtmlAgilityPack.NetCore.

**Comment by mysticmind** [comment]
@agatlin My forked version targeting .Net core is also used by several folks, see the Nuget download stats for https://www.nuget.org/packages/MysticMind.HtmlAgilityPack/. So  don't worry about this lib.

**Comment by PromoFaux** [comment]
@mysticmind, is this still necessary? Currently causing conflicts when using other nuget packages that depend on HtmlAgilityPack such as this: https://github.com/codehollow/FeedReader/
