### ISSUE TITLE
UnknownTagsOption issue

### ISSUE THREAD

**Issue by Tharkis** [mysticmind/reversemarkdown-net#60]
There appears to be an issue with handling unknown tags. No matter which option is chosen, the uknown tag seems to be processed as Passthrough. 

Example:
`This text has a<sup>"sup"</sup> tag.`

When it's processed, the <sup> tag remains regardless of whether I pass Drop or Bypass. Exceptions do not get thrown when Raise is chosen.

Am I missing something?

**Comment by mysticmind** [comment]
Let me check and keep you posted.

**Comment by mysticmind** [comment]
There is already unit tests for each case and the config options for unknown tags are working as expected. Could you please provide a repro use case?

**Comment by Tharkis** [comment]
As it turns out, I wasn't passing the config so it was evaluating everything with the default options.

I appreciate the quick reply, sorry to have bothered you.
