### ISSUE TITLE
Convert inline style "font-weight: bold" to **bold**

### ISSUE THREAD

**Issue by icnocop** [mysticmind/reversemarkdown-net#66]
I'd like to request a new feature to support converting inline `font-weight: bold` style to markdown `**bold**`.

```
        [TestMethod]
        public void ConvertInlineStyleFontWeightBold()
        {
            string html = @"
            <html>
                <body>
                    <p style=""font-weight: bold;"">Hello World</p>
                </body>
            </html>";

            var config = new Config();
            Converter converter = new Converter(config);
            string markdown = converter.Convert(html).Trim();

            Assert.AreEqual("**Hello World**", markdown);
        }
```

## Expected

I expected `<p style="font-weight: bold;">Hello World</p>` to be converted to `**Hello World**`.

## Actual

`<p style="font-weight: bold;">Hello World</p>` is converted to `Hello World`.

Thank you.

**Comment by icnocop** [comment]
I'm able to pre-process the HTML using the code example here:
https://stackoverflow.com/a/18953078/90287

😃

**Comment by mysticmind** [comment]
@icnocop Glad to hear that you are able to sort it out with a pre-processing step. The library never dealt with processing styles so far.
