### ISSUE TITLE
Unexpected markdown when converting HTML with <br/> inside <b>

### ISSUE THREAD

**Issue by icnocop** [mysticmind/reversemarkdown-net#67]
I receive unexpected markdown when converting HTML with `<br/>` inside `<b>`.

# Steps to reproduce
```
        [TestMethod]
        public void test()
        {
            string html = "test<b><br/>test</b>";

            Converter converter = new Converter();

            string markdown = converter.Convert(html);

            Assert.AreEqual("test**  \r\ntest**", markdown);
        }
```

# Expected

I expected `test<b><br/>test</b>` to be converted to the following markdown:
```
test**  
test**
```

# Actual

`test<b><br/>test</b>` is converted to `test**test**`.

I'm using v3.11.0.

Thank you.

**Comment by mysticmind** [comment]
@icnocop  I will have a look at it this week, sorry about the delay in responding on this issue.

**Comment by mysticmind** [comment]
Fixed via https://github.com/mysticmind/reversemarkdown-net/commit/ee245d8f88559cf403db8808f28cec344b34d03c

**Comment by mysticmind** [comment]
v3.12.0 is available in NuGet

**Comment by mos379** [comment]
@mysticmind isn't this wrong translation? 

as far as I understand if the starting and ending element are on different lines, then they don't get parsed when translating back to html?

**Comment by mysticmind** [comment]
@mos379 you are right, it is a wrong translation. Planning to spend some time this week on ReverseMarkdown, will attempt to reply/address on the open issues. Please do open a new issue for this.
