### ISSUE TITLE
Images within links have escape characters added

### ISSUE THREAD

**Issue by MikeCardiff** [mysticmind/reversemarkdown-net#69]
Firstly, thank you for you work on this project. I've just looked at integrating with something I'm working on and noticed an issue.

If an `img` tag is contained within an `a` tag, the resulting Markdown has escape characters added.

Code to reproduce:
```csharp
var converter = new ReverseMarkdown.Converter();
var result = converter.Convert("<a href=\"https://www.example.com\"><img src=\"https://example.com/image.jpg\"/></a>");
```
Expected Result:
```
[![](https://example.com/image.jpg)](https://www.example.com)
```

Actual Result:
```
[!\[\](https://example.com/image.jpg)](https://www.example.com)
```

I'm not familiar with the code, but from a quick look it's possibly being escaped in the `EscapeLinkText` method here:
https://github.com/mysticmind/reversemarkdown-net/blob/911561aaed1bf59cb65c980581ce4402906bafde/src/ReverseMarkdown/Converters/A.cs#L44

**Comment by mysticmind** [comment]
@MikeCardiff thanks for reporting the issue, will take a look at it this week and keep; you posted.

**Comment by mysticmind** [comment]
@MikeCardiff I had a look the issue which you have posted. My observations are as below:
-  Link text should not contain a nested link/image i.e. it is simple text. The expected result which you have posted is an invalid markdown.
- The current implementation ensure that it is just text hence it got escaped.

Probably you will need to pre-process the html to remove `a` tag containing an `img` tag as text.

I am closing the same as invalid. please let me know your thoughts.

**Comment by mysticmind** [comment]
Fixed via https://github.com/mysticmind/reversemarkdown-net/commit/4b8419b04839c9b6ffa76fd245e6323b023425e7

**Comment by mysticmind** [comment]
v3.12.0 is available in NuGet

**Comment by MikeCardiff** [comment]
@mysticmind I've just tried the updated NuGet with a console app and can confirm that images inside links are rendering as expected.

Thank you for looking into this and working on a fix.
