### ISSUE TITLE
Preserving whitespace (newlines) between PRE tags. 

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mysticmind/reversemarkdown-net#74]
I'm trying to parse HTML and convert to markdwon a simple page. Is there a way to preserve whitespace within pre tags? At the moment pre tags are converted to one big line which is not at all ideal.

I tried to modify your code a bit by adding:

```c#
            var doc = new HtmlDocument();
            doc.OptionWriteEmptyNodes = true;
            doc.LoadHtml(html);
```

but it didn't help. Here's a snippet:

```html
<p>Hi there</p>
<p>Sometimes we got simply calls to list the following data from ADDS - Active Directory Domain Users:</p>
<p>Total Users in ADDS forest / domain</p>
<p>Total Disabled Users in&nbsp;ADDS forest / domain</p>
<p>Total Enabled Users in&nbsp;ADDS forest / domain</p>
<p>In general you can use PowerShell remote to do so or you can connect direct using RDP (remote desktop services) into a specific DC (Domain Controller) to pull out this data request.</p>
<p>If your environment has <a href="https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/jea/overview?view=powershell-7">
JEA - Just Enough Administration </a>be aware of limitations on powershell commands against specified Servers' roles and features.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<pre class="hidden">###############################################################################################################################################################################################################################################
# Author Thiago Beier thiago.beier@gmail.com   
# Version: 1.0 - 2020-03-09  
# List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
# Toronto, CANADA   
# Email: thiago.beier@gmail.com 
# https://www.linkedin.com/in/tbeier/ 
# https://twitter.com/thiagobeier
# thiagobeier.wordpress.com
###############################################################################################################################################################################################################################################  

#Get-ADUser -Filter * -SearchBase &quot;OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local&quot; |fl name | measure
$userstotal = Get-ADUser -Filter * -SearchBase &quot;DC=canada,DC=local&quot; |fl name | measure
$usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
$usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
write-host -ForegroundColor Magenta &quot;########################## ADDS - TGAM - Users Report ###########################&quot;
Write-Host -ForegroundColor Yellow &quot;Total Users&quot; $userstotal.Count
Write-Host -ForegroundColor Green &quot;Enabled Users&quot; $usersenabled.Count
Write-Host -ForegroundColor Cyan &quot;Disabled Users&quot; $usersdisabled.Count
write-host -ForegroundColor Magenta &quot;#################################################################################&quot;</pre>
```

Here's full page:
[PageProjectDescription.zip](https://github.com/mysticmind/reversemarkdown-net/files/5033591/PageProjectDescription.zip)

Any way to get this working?

**Comment by mysticmind** [comment]
Acknowledge the issue which you have posted, let me check and ck to you shortly.

**Comment by mysticmind** [comment]
@PrzemyslawKlys I have applied a local fix in my dev and providing the output below. please confirm if it looks fine.



    ###############################################################################################################################################################################################################################################
    # Author Thiago Beier thiago.beier@gmail.com   
    # Version: 1.0 - 2020-03-09  
    # List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
    # Toronto, CANADA   
    # Email: thiago.beier@gmail.com 
    # https://www.linkedin.com/in/tbeier/ 
    # https://twitter.com/thiagobeier
    # thiagobeier.wordpress.com
    ###############################################################################################################################################################################################################################################  
    
    #Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
    $userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
    $usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
    $usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
    write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
    Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
    Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
    Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
    write-host -ForegroundColor Magenta "#################################################################################"




    <span class="powerShell__com">###############################################################################################################################################################################################################################################</span> 
    <span class="powerShell__com"># Author Thiago Beier thiago.beier@gmail.com   </span> 
    <span class="powerShell__com"># Version: 1.0 - 2020-03-09  </span> 
    <span class="powerShell__com"># List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13</span> 
    <span class="powerShell__com"># Toronto, CANADA   </span> 
    <span class="powerShell__com"># Email: thiago.beier@gmail.com </span> 
    <span class="powerShell__com"># https://www.linkedin.com/in/tbeier/ </span> 
    <span class="powerShell__com"># https://twitter.com/thiagobeier</span> 
    <span class="powerShell__com"># thiagobeier.wordpress.com</span> 
    <span class="powerShell__com">###############################################################################################################################################################################################################################################  </span> 
     
    <span class="powerShell__com">#Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure</span> 
    <span class="powerShell__variable">$userstotal</span> = Get<span class="powerShell__operator">-</span>ADUser <span class="powerShell__operator">-</span><span class="powerShell__keyword">Filter</span> <span class="powerShell__operator">*</span> <span class="powerShell__operator">-</span>SearchBase <span class="powerShell__string">"DC=canada,DC=local"</span> <span class="powerShell__operator">|</span><span class="powerShell__alias">fl</span> name <span class="powerShell__operator">|</span> measure 
    <span class="powerShell__variable">$usersenabled</span> = Get<span class="powerShell__operator">-</span>ADUser <span class="powerShell__operator">-</span><span class="powerShell__keyword">Filter</span> {Enabled <span class="powerShell__operator">-</span>eq <span class="powerShell__variable">$true</span>} <span class="powerShell__operator">|</span> <span class="powerShell__alias">fl</span> name <span class="powerShell__operator">|</span> measure 
    <span class="powerShell__variable">$usersdisabled</span> = Get<span class="powerShell__operator">-</span>ADUser <span class="powerShell__operator">-</span><span class="powerShell__keyword">Filter</span> {Enabled <span class="powerShell__operator">-</span>eq <span class="powerShell__variable">$false</span>} <span class="powerShell__operator">|</span> <span class="powerShell__alias">fl</span> name <span class="powerShell__operator">|</span> measure 
    write<span class="powerShell__operator">-</span>host <span class="powerShell__operator">-</span>ForegroundColor Magenta <span class="powerShell__string">"########################## ADDS - TGAM - Users Report ###########################"</span> 
    Write<span class="powerShell__operator">-</span>Host <span class="powerShell__operator">-</span>ForegroundColor Yellow <span class="powerShell__string">"Total Users"</span> <span class="powerShell__variable">$userstotal</span>.Count 
    Write<span class="powerShell__operator">-</span>Host <span class="powerShell__operator">-</span>ForegroundColor Green <span class="powerShell__string">"Enabled Users"</span> <span class="powerShell__variable">$usersenabled</span>.Count 
    Write<span class="powerShell__operator">-</span>Host <span class="powerShell__operator">-</span>ForegroundColor Cyan <span class="powerShell__string">"Disabled Users"</span> <span class="powerShell__variable">$usersdisabled</span>.Count 
    write<span class="powerShell__operator">-</span>host <span class="powerShell__operator">-</span>ForegroundColor Magenta <span class="powerShell__string">"#################################################################################"</span>

**Comment by PrzemyslawKlys** [comment]
Yes. The first PRE is the one I need, the 2nd pre is one that seems to be doing coloring (so doubled code). Is there a way to "pick" which one I want? 

Is there a way I can test it on more files? (I've got like few thousands of them).

**Comment by PrzemyslawKlys** [comment]
As additional question - will your code convert link within <P> tags to markdown as well?

**Comment by mysticmind** [comment]
> 
> 
> Yes. The first PRE is the one I need, the 2nd pre is one that seems to be doing coloring (so doubled code). Is there a way to "pick" which one I want?
> 
> Is there a way I can test it on more files? (I've got like few thousands of them).

With regards to picking which one you want, you have to run a pre-process step (using something like [HtmlAgilityPack](https://html-agility-pack.net/)) to remove what you don't need from the html and then pass it to the converter.

The attached zip file contains the NuGet package file which you can use for your tests. Unzip into a folder and add the folder as a NuGet source to use
[ReverseMarkdown.3.13.0-test.zip](https://github.com/mysticmind/reversemarkdown-net/files/5036220/ReverseMarkdown.3.13.0-test.zip)

**Comment by PrzemyslawKlys** [comment]
Is it possible to provide language flavor for PRE tags?

**Comment by mysticmind** [comment]
> 
> 
> As additional question - will your code convert link within `<P>` tags to markdown as well?

Any child elements of anchor tag gets processed. Please run a test with your use case and let me know your results.

**Comment by mysticmind** [comment]
> 
> 
> Is it possible to provide language flavor for PRE tags? So one can decide if it's powershell, c#, js or something else?

Language parsing will work if you use Github flavoured markdown with the config below:
```
var config = new Config
{
    GithubFlavored = true
};
```

Look at some of the examples in in [unit tests](https://github.com/mysticmind/reversemarkdown-net/blob/master/src/ReverseMarkdown.Test/ConverterTests.cs). Search for language.

**Comment by PrzemyslawKlys** [comment]
Ye, but I mean giving it a name. Such as:

```powershell
###############################################################################################################################################################################################################################################
# Author Thiago Beier thiago.beier@gmail.com   
# Version: 1.0 - 2020-03-09  
# List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
# Toronto, CANADA   
# Email: thiago.beier@gmail.com 
# https://www.linkedin.com/in/tbeier/ 
# https://twitter.com/thiagobeier
# thiagobeier.wordpress.com
###############################################################################################################################################################################################################################################  

#Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
$userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
$usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
$usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
write-host -ForegroundColor Magenta "#################################################################################"
```

I've used GitHubFlavored and it just gave me ``` which is enough, but cooler would be with PowerShell formatting. 

```
###############################################################################################################################################################################################################################################
# Author Thiago Beier thiago.beier@gmail.com   
# Version: 1.0 - 2020-03-09  
# List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
# Toronto, CANADA   
# Email: thiago.beier@gmail.com 
# https://www.linkedin.com/in/tbeier/ 
# https://twitter.com/thiagobeier
# thiagobeier.wordpress.com
###############################################################################################################################################################################################################################################  

#Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
$userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
$usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
$usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
write-host -ForegroundColor Magenta "#################################################################################"
```

**Comment by mysticmind** [comment]
> 
> 
> Ye, but I mean giving it a name. Such as: `` ```powershell ``
> 
> ```powershell
> ###############################################################################################################################################################################################################################################
> # Author Thiago Beier thiago.beier@gmail.com   
> # Version: 1.0 - 2020-03-09  
> # List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
> # Toronto, CANADA   
> # Email: thiago.beier@gmail.com 
> # https://www.linkedin.com/in/tbeier/ 
> # https://twitter.com/thiagobeier
> # thiagobeier.wordpress.com
> ###############################################################################################################################################################################################################################################  
> 
> #Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
> $userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
> $usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
> $usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
> write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
> Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
> Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
> Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
> write-host -ForegroundColor Magenta "#################################################################################"
> ```
> 
> I've used GitHubFlavored and it just gave me ``` which is enough, but cooler would be with PowerShell formatting.
> 
> ```
> ###############################################################################################################################################################################################################################################
> # Author Thiago Beier thiago.beier@gmail.com   
> # Version: 1.0 - 2020-03-09  
> # List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
> # Toronto, CANADA   
> # Email: thiago.beier@gmail.com 
> # https://www.linkedin.com/in/tbeier/ 
> # https://twitter.com/thiagobeier
> # thiagobeier.wordpress.com
> ###############################################################################################################################################################################################################################################  
> 
> #Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
> $userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
> $usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
> $usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
> write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
> Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
> Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
> Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
> write-host -ForegroundColor Magenta "#################################################################################"
> ```

if your pre tag has any language marker class then it will add the language to the fenced code. See the examples in unit tests. Also you can see the [Pre.cs](https://github.com/mysticmind/reversemarkdown-net/blob/d6248b4b3374dcd7920c7602aa8738b20f4a388d/src/ReverseMarkdown/Converters/Pre.cs#L41) to see how this works.

**Comment by PrzemyslawKlys** [comment]
I see, it doesn't. Would it be possible to add an option to overwrite it? (as in always set it to given value)?

**Comment by mysticmind** [comment]
> 
> 
> I see, it doesn't. Would it be possible to add an option to overwrite it? (as in always set it to given value)?

The way for you to make it work is to pre-process step to massage the html to add the language class to `pre` tag and then send it to the converter to process the same.

**Comment by PrzemyslawKlys** [comment]
The output:

![image](https://user-images.githubusercontent.com/15063294/89558666-c8ead480-d814-11ea-889e-3ac7db8cb825.png)

It doesn't seem to do it properly. So either you sent me wrong version or I'm doing something wrong. Also it seems that 2x new line is added for <p></p> tags

**Comment by mysticmind** [comment]
> 
> 
> The output:
> 
> ![image](https://user-images.githubusercontent.com/15063294/89558666-c8ead480-d814-11ea-889e-3ac7db8cb825.png)
> 
> It doesn't seem to do it properly. So either you sent me wrong version or I'm doing something wrong. Also it seems that 2x new line is added for
> 
> tags

I am heading to bed now, will check and revert to you tomorrow.

**Comment by PrzemyslawKlys** [comment]
Any luck?

**Comment by mysticmind** [comment]
Hey, sorry, got held with a lot of personal work, will revert to in a day
or so. This is still in my radar.

**Comment by mysticmind** [comment]
@PrzemyslawKlys quick note, I will be spending time on this today to try and sort it out, please await for an update from me later today.

**Comment by PrzemyslawKlys** [comment]
Thank you. Take your time. Personal stuff is more important! I am not in hurry.

**Comment by mysticmind** [comment]
I am re-reading the responses from you and looks like using `GitHubFlavored ` gives you the right output albeit you want the language marker. There are 2 ways to achieve this, 1)you can do a pre-process step to add class `highlight-powershell` to the parent div in your content like below:
```
<div class="highlight-powershell">
<pre>....</pre>
</div>
```

Or as your requested, a config can be added to include a default language if one is not found.

In summary, the latter to add config is a trivial thing to do. If you can make do with the pre-processing, it is also fine. Let me know your thoughts.

**Comment by PrzemyslawKlys** [comment]
It's not giving right output. If you check the screen shot (last one) - it's all in one line. PowerShell doesn't work like that and line breaks are nessecary.

**Comment by mysticmind** [comment]
> 
> 
> Ye, but I mean giving it a name. Such as: `` ```powershell ``
> 
> ```powershell
> ###############################################################################################################################################################################################################################################
> # Author Thiago Beier thiago.beier@gmail.com   
> # Version: 1.0 - 2020-03-09  
> # List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
> # Toronto, CANADA   
> # Email: thiago.beier@gmail.com 
> # https://www.linkedin.com/in/tbeier/ 
> # https://twitter.com/thiagobeier
> # thiagobeier.wordpress.com
> ###############################################################################################################################################################################################################################################  
> 
> #Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
> $userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
> $usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
> $usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
> write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
> Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
> Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
> Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
> write-host -ForegroundColor Magenta "#################################################################################"
> ```
> 
> I've used GitHubFlavored and it just gave me ``` which is enough, but cooler would be with PowerShell formatting.
> 
> ```
> ###############################################################################################################################################################################################################################################
> # Author Thiago Beier thiago.beier@gmail.com   
> # Version: 1.0 - 2020-03-09  
> # List sum of total users, total enabled accounts, total disabled accounts in ADDS (you can restrict the search to a specific OU - line 12 and 13
> # Toronto, CANADA   
> # Email: thiago.beier@gmail.com 
> # https://www.linkedin.com/in/tbeier/ 
> # https://twitter.com/thiagobeier
> # thiagobeier.wordpress.com
> ###############################################################################################################################################################################################################################################  
> 
> #Get-ADUser -Filter * -SearchBase "OU=Field,OU=Users,OU=Toronto,DC=canada,DC=local" |fl name | measure
> $userstotal = Get-ADUser -Filter * -SearchBase "DC=canada,DC=local" |fl name | measure
> $usersenabled = Get-ADUser -Filter {Enabled -eq $true} | fl name | measure
> $usersdisabled = Get-ADUser -Filter {Enabled -eq $false} | fl name | measure
> write-host -ForegroundColor Magenta "########################## ADDS - TGAM - Users Report ###########################"
> Write-Host -ForegroundColor Yellow "Total Users" $userstotal.Count
> Write-Host -ForegroundColor Green "Enabled Users" $usersenabled.Count
> Write-Host -ForegroundColor Cyan "Disabled Users" $usersdisabled.Count
> write-host -ForegroundColor Magenta "#################################################################################"
> ```

I meant to refer to this output which you have posted using the version published in NuGet. Ignore the test build which I provided you which seems to be messing up with the  line breaks.

**Comment by mysticmind** [comment]
BTW, I am adding the config option `DefaultCodeBlockLanguage` which you can set. If language is not detectable using the class names or if it is missing, the above config will come into play when `GithubFlavored` option is used. I believe, this should help with you use case.

**Comment by PrzemyslawKlys** [comment]
That's great! It will help a lot.

**Comment by mysticmind** [comment]
`DefaultCodeBlockLanguage` option added via https://github.com/mysticmind/reversemarkdown-net/commit/f82cdadffc92b93bf8a51f662fff37bf8d0c3511

**Comment by mysticmind** [comment]
@PrzemyslawKlys I have released v3.13.0 to NuGet. Please run your use case with `GithubFlavored = true` and `DefaultCodeBlockLanguage = "powershell"` and please let me know if it yields the desired result.

**Comment by PrzemyslawKlys** [comment]
DefaultCodeBlockLanguage works. Adding spaces, doesn't. 



Here's another example:
![image](https://user-images.githubusercontent.com/15063294/90112844-ce827600-dd50-11ea-9598-e7ec5377d6f5.png)

[PageProjectDescription.zip](https://github.com/mysticmind/reversemarkdown-net/files/5067980/PageProjectDescription.zip)

if you click on the .HTML you will see the output is ok. But markdown seems to ignore it.

**Comment by mysticmind** [comment]
@PrzemyslawKlys I understand the issue what you have highlighted. Trying to workout a solution.

**Comment by mysticmind** [comment]
@PrzemyslawKlys I had to revamp the whole implementation of `pre` to handle few varying use cases including yours. Can you please try with the one attached and let me know
[ReverseMarkdown.3.14.0.zip](https://github.com/mysticmind/reversemarkdown-net/files/5068994/ReverseMarkdown.3.14.0.zip)

Once you confirm, I will plan to do a release to NuGet.

**Comment by PrzemyslawKlys** [comment]
There's no DLL packed :-) just PDB files

**Comment by mysticmind** [comment]
My bad, sorry about, please check the below:
[ReverseMarkdown.3.14.0.zip](https://github.com/mysticmind/reversemarkdown-net/files/5069372/ReverseMarkdown.3.14.0.zip)

**Comment by PrzemyslawKlys** [comment]
No change. Still the same output :(

**Comment by mysticmind** [comment]
hmm. something is a miss. I have attached the file and the output for your reference. Can you please check the output on the attached file?
[output.zip](https://github.com/mysticmind/reversemarkdown-net/files/5069578/output.zip)

Also can you please share the output generated on your end as a file?

**Comment by mysticmind** [comment]
I have added added the code changes in a feature branch for referernce https://github.com/mysticmind/reversemarkdown-net/tree/revamp_pre_tag_converter.

**Comment by PrzemyslawKlys** [comment]
Ye, yours look correct. 

This is the final config before I use it. 
```
UnknownTags                   : Drop
GithubFlavored                : True
RemoveComments                : False
WhitelistUriSchemes           :
SmartHrefHandling             : False
TableWithoutHeaderRowHandling : Default
ListBulletChar                : -
DefaultCodeBlockLanguage      : powershell
```

Now, it worked. You know I'm using your library in PowerShell (wrote module around it) 

This works, and preserves spaces
```powershell
$Content = Get-Content -Path $Path -Raw
```

This doesn't work, as in your library doesn't seem to be able to find linefeeds. 
```powershell
$Content = Get-Content -Path $Path
```
My fault!

**Comment by mysticmind** [comment]
Glad that you have got it working 👏 
I will release v3.14.0 in my morning tomo.

**Comment by mysticmind** [comment]
Added some refactoring, fixed via https://github.com/mysticmind/reversemarkdown-net/commit/cb4afb43b2b9c0902f283db9d27348f52f9f2450

**Comment by mysticmind** [comment]
v3.14.0 is available in NuGet. Looking at your html samples, I manage to squeeze in some enhancements as well, you can check the release notes [here](https://github.com/mysticmind/reversemarkdown-net/releases/tag/3.14.0)
