### ISSUE TITLE
Process only body tag content in html and ignore head and other elements

### ISSUE THREAD

**Issue by mysticmind** [mysticmind/reversemarkdown-net#77]

**Comment by mysticmind** [comment]
Fixed via https://github.com/mysticmind/reversemarkdown-net/commit/69d13e867122b9a6fdac0104a33bf3490ebc1c10

**Comment by PrzemyslawKlys** [comment]
Could this be maybe an option? I could see some people maybe wanting to convert Title and other stuff from Head to proper markdown?

**Comment by mysticmind** [comment]
If we have more details/use cases around this, we can workout the required
implementation.

**Comment by PrzemyslawKlys** [comment]
I was thinking one may want to support tags from head:
- title
- meta (https://www.w3schools.com/tags/tag_meta.asp) - author/description/keywords

But again, this should be an option, because not always it contains data or is useful
