### ISSUE TITLE
Why HAP instead of AngleSharp?

### ISSUE THREAD

**Issue by aloisdg** [mysticmind/reversemarkdown-net#8]
(title)

**Comment by mysticmind** [comment]
I had more familiarity and experience using HAP in several projects hence had used it. Do you see any compelling reason to use AngleSharp instead of HAP?

**Comment by aloisdg** [comment]
[Well](https://github.com/AngleSharp/AngleSharp/wiki/Performance#comparison-with-the-htmlagilitypack)

**Comment by mysticmind** [comment]
Thanks for the link, read through the details and sounds like a great replacement lib for HAP. 

I am working to gather some baseline performance numbers using BenckmarkDotNet on the current version before I work on applying few performance fixes. I will also look at creating a feature branch with AngleSharp integration, measure performance. Evaluate all the performance numbers to take a call on next steps.

Appreciate your question and the conversation.

**Comment by aloisdg** [comment]
I am glad if I could help you. :)

**Comment by mysticmind** [comment]
AngleSharp integration is not in the radar at this juncture and benchmarking is not yet done for HAP. Closing this for now.
