### ISSUE TITLE
STRONG tags next to each other 

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mysticmind/reversemarkdown-net#84]
[PageProjectDescription.zip](https://github.com/mysticmind/reversemarkdown-net/files/5102631/PageProjectDescription.zip)

Are converted to this:
```markdown
**Command usage examples: ****[Samples.PNG](DownloadContent\Samples.PNG)**

**Sample Log file: [Samples2.PNG](DownloadContent\Samples2.PNG)**
```

This makes me think if two or more tags are next to each other you would need to add space.

**Comment by mysticmind** [comment]
Fixed via 3695ad11825ab52e96b33f52597f14c2f3c81f5e
