### ISSUE TITLE
Allow to choose attributes for parsing PRE tag

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mysticmind/reversemarkdown-net#85]
Here's my use case:

```html
<pre class="vb">Const NO_VALUE = Empty

Set WshShell = WScript.CreateObject(&quot;WScript.Shell&quot;)
WshShell.RegWrite _
    &quot;HKLM\System\CurrentControlSet\Services\EventLog\Scripts\&quot;, NO_VALUE
</pre>
```

As you can see class is used for syntax highlighting. Could you add support for it from Class or ability to configure attribute if it not possible automatically? 

Some information on possible options: https://stackoverflow.com/questions/5134242/semantics-standards-and-using-the-lang-attribute-for-source-code-in-markup

**Comment by mysticmind** [comment]
You can do a preprocess step by loading the content into HtmlAgilityPack and changing the `class` attribute to use one of the below supported language classes:
- Confluence language class `brush: python`
- Github Site language class `highlight highlight-source-csharp`
- HighlightJs language class `hljs language-csharp`

I am closing this.
